# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyNewCrashlytics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyNewCrashlytics
pod 'Firebase/Analytics'
pod 'Crashlytics', '~> 3.13.2'  #use this version only

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

end
